### PR TITLE
fix(dependencies): aws sdk v3 packages are dependencies not devDependencies

### PR DESCRIPTION
**Pull request by oieduardorabelo**
- related to issue https://github.com/jeremydaly/lambda-api/issues/229
- ran `prettier` in code to fix failing ci https://github.com/jeremydaly/lambda-api/actions/runs/4388737872/jobs/7685568423

cc @naorpeled

### CODE REVIEW

**Comment by naorpeled** [comment]
Hey @oieduardorabelo,

first of all, thank you for this!

could you move them to be peer dependencies instead?

**Comment by oieduardorabelo** [comment]
back to you @naorpeled

**Review by naorpeled — APPROVED** [review]

**Comment by oieduardorabelo** [comment]
the ci is failing because the version of npm in node 14 is less than 7:

https://github.com/jeremydaly/lambda-api/actions/runs/4399624238/jobs/7704331228

npm 7+ install peer dependencies by default, npm 6 and below don't

@naorpeled

**Comment by naorpeled** [comment]
> the ci is failing because the version of npm in node 14 is less than 7:
> 
> https://github.com/jeremydaly/lambda-api/actions/runs/4399624238/jobs/7704331228
> 
> npm 7+ install peer dependencies by default, npm 6 and below don't
> 
> @naorpeled 

Let's set a custom npm version in CI then, wdyt?

**Comment by oieduardorabelo** [comment]
https://github.com/jeremydaly/lambda-api/pull/231/commits/6de19b783b87dfbffbaea97543038b0d4956110f

@naorpeled

**Pull request merged**
