### PR TITLE
Define overloads for LoggerFunction in type definition

### PR DESCRIPTION
**Pull request by Sleavely**
I converted a route to Typescript and things went 💥 

Turns out the type definition for the logger methods only expects a string.

This PR makes it behave in accordance with the [README](https://github.com/jeremydaly/lambda-api#adding-additional-detail)

### CODE REVIEW

**Comment by brighttank** [comment]
Is there an update on this?

**Comment by Sleavely** [comment]
Needs review/merge by @jeremydaly

**Comment by naorpeled** [comment]
Hey @Sleavely,
thanks for your contribution,
this issue was already resolved in a different PR that I've merged,
in addition we allow several params and not only two so this code is not correct.

Again, thanks and sorry for the delayed response 🙏

**Comment by Sleavely** [comment]
No worries, I'm just glad the issue is being looked at :)

> in addition we allow several params and not only two so this code is not correct.

From what I understand, the abstract logger supports a dynamic amount of arguments while the actual implementation in the `Request` object explicitly only accepts two?

https://github.com/jeremydaly/lambda-api/blob/85a8654e3592fde4436cc49919a1b2678a1a3af7/lib/request.js#L54

**Comment by naorpeled** [comment]
Hey @Sleavely,
I've dug into this a bit further and you're correct, I misunderstood that part in the code, good catch.

I'll be opening a new PR

**Pull request closed without merging**
