### PR TITLE
Add middleware type to api handler

### PR DESCRIPTION
**Pull request by billjohnston**

### CODE REVIEW

**Comment by jrbarnard** [comment]
It would be good to get someones eyes on this or just getting the type definitions fixed @naorpeled

**Comment by naorpeled** [comment]
> It would be good to get someones eyes on this or just getting the type definitions fixed @naorpeled 

Hey!
Will be able to take a look tomorrow hopefully

**Comment by naorpeled** [comment]
Hey @jrbarnard,
started working on improving the type defs in #235 

Will continue tomorrow

**Comment by naorpeled** [comment]
@billjohnston thanks for your contribution bud,
created a new PR with a minor fix and co-authored you.

@jrbarnard the fix will be released today :)

**Pull request closed without merging**
