### PR TITLE
typescript support for issue #32

### PR DESCRIPTION
**Pull request by jimsorock**

### CODE REVIEW

**Comment by jimsorock** [comment]
Hi @jeremydaly! Just a friendly bump if you have time to check this out! Thanks for the awesome work.

**Comment by jimsorock** [comment]
@jeremydaly Hi is this something that an be reviewed and merged? Thanks!

**Comment by cameroncf** [comment]
I've just run into this and happy to see this PR to resolve it. This library is fantastic. Looking forward to working with it more!

**Comment by jimsorock** [comment]
Bump @jeremydaly

**Review by naorpeled — APPROVED** [review]

**Comment by naorpeled** [comment]
Hey @jimsorock,
thanks for your contribution, you're amazing 😎

**Pull request merged**
