### PR TITLE
Fix Logger is not handling missing context

### PR DESCRIPTION
**Pull request by RWhite-EDR**
Logger is not handling missing context...
https://github.com/jeremydaly/lambda-api/issues/260

### CODE REVIEW

**Comment by naorpeled** [comment]
Hey @RWhite-EDR ,
first of all, thanks for this!

Can you please add a unit test to verify this?

**Comment by RWhite-EDR** [comment]
@naorpeled I'm not sure if I can as the context object is almost always present.  It is only missing in my unit test of my routes.  I've never seen this issue from within API Gateway, ALB, or serverless-offline.  Only in my jest-based unit tests.

**Comment by naorpeled** [comment]
Hey @RWhite-EDR 
will make a minor change tomorrow and then release this 🙏 

Sorry for the delay

**Comment by naorpeled** [comment]
Hey @RWhite-EDR,
I gave this some more thought and I think that because this isn't a real use case we shouldn't really support it.
Sorry for the confusion and thanks for your time.

**Comment by RWhite-EDR** [comment]
@naorpeled Rats -- so close.  I'm not sure why testing of the main function using Jest isn't a real use case.  Maybe I need a better mock, but I can show you where this is failing from my test scripts.

**Pull request closed without merging**
