### PR TITLE
Automatic Compression

### PR DESCRIPTION
**Pull request by AndrewBarba**
Automatically compress responses based on the `Accept-Encoding` header:

```javascript
const api = require('lambda-api')({
  compression: true
})
```

### CODE REVIEW

**Comment by jeremydaly** [comment]
Hey @AndrewBarba, thanks for your work on this. Adding the `zlib` library breaks the **ZERO DEPENDENCY** rule, plus the package has been deprecated because the functionality has been rolled into Node.js CORE: https://nodejs.org/dist/latest/docs/api/zlib.html

I'm going to work on refactoring this and merging it into the main branch without the extra dependency.

**Comment by jeremydaly** [comment]
FYI, moving this work into a new `zlib` branch. https://github.com/jeremydaly/lambda-api/tree/zlib

**Comment by AndrewBarba** [comment]
@jeremydaly I didn't add any deps, this is using zlib built into Node.js

**Comment by AndrewBarba** [comment]
Curious why you think I added a new deb in the first place. Is something off in the git diff?

**Comment by jeremydaly** [comment]
This is failing on Travis because the node version is still at `8`. 😬

Updating that now.

**Pull request merged**
