### PR TITLE
Support Custom Serializer with Base64 Encoded Response

### PR DESCRIPTION
**Pull request by AndrewBarba**
This adds the ability to return a gzipped response to lambda:

```javascript
const api = require('lambda-api')({
  isBase64: true,
  headers: {
    'content-encoding': ['gzip']
  },
  serializer: body => {
    const json = JSON.stringify(body)
    return zlib.gzipSync(json).toString('base64')
  }
})
```

Inspiration: https://medium.com/@vanbergstephane/gzip-aws-lambda-http-api-gateway-6b9c6431c564

### CODE REVIEW

**Comment by jeremydaly** [comment]
Thanks @AndrewBarba. I'll take a look and get this merged.

**Comment by AndrewBarba** [comment]
@jeremydaly Thanks a lot. It should be good to go at this point. I have this deployed and its working as expected, all tests (including a new one) pass, and I added compression docs to the readme.

**Comment by jeremydaly** [comment]
I was just going to ask you to add documentation! 🙌 I’ve also added another test to the error handling to ensure base64 was flagged correctly. I’ll check that in soon, merge this all, and push to npm.

**Comment by jeremydaly** [comment]
v0.10.7 is now in npm.

**Pull request merged**
